### ISSUE TITLE
is bitpocket still maintained ?

### ISSUE THREAD

**Issue by jpcaruana** [sickill/bitpocket#43]
Hi,
is bitpocket still maintained ? If not, is there any official fork ?
It's a nice tool

thanks

**Comment by sickill** [comment]
We have several open issues and PRs that need looking into. I don't really have time for this project anymore. What about you @torfason? Should we look for new maintainers?

**Comment by torfason** [comment]
Unfortunately I'm in the same situation, I won't realistically manage any pull requests. I'd second getting new maintainers if any are to be found ...
