### ISSUE TITLE
bitsync fail on backup

### ISSUE THREAD

**Issue by yotama9** [sickill/bitpocket#65]
since yesterday, bitsync fails to backup my local folders. I get the following error

    Saving current state and backing up files (if needed)
    | Root dir: /home/yotam/Sync
    sh: 5: Syntax error: "fi" unexpected (expecting "then")
    fatal: command failed BACKUP

The message first appeared when I was working on my server machine, but I was working the previous day as well and there weren't any issues then.

**Comment by greezybacon** [comment]
Sorry it's not working. Can you share some version information about your bitpocket? Perhaps `git rev-parse HEAD`? Or maybe when you downloaded it?

**Comment by yotama9** [comment]
Hi. Thank you for the reply. Here is the ``HEAD`` you asked for:

     git rev-parse HEAD
     7854553182dc932524eb240f6e856fd69e7f6a0f

**Comment by yotama9** [comment]
In the meantime, how can reactivate the sync?

**Comment by greezybacon** [comment]
@yotama9 I think you should download and replace the original script. Looks like it was likely corrupted.

https://github.com/sickill/bitpocket/raw/7854553182dc932524eb240f6e856fd69e7f6a0f/bin/bitpocket

**Comment by yotama9** [comment]
I updated the git repository of bitpocket and things work now.Thanks.
